#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2026.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 10 15:04:03 PDT 2026
# SW Build 6511674 on Tue Jun 16 11:01:26 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2026.1
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim csa_multiplierSIM_behav -key {Behavioral:sim_1:Functional:csa_multiplierSIM} -tclbatch csa_multiplierSIM.tcl -view /home/pmyers/Documents/F26files/3300/MultiplierCalculator/csa_multiplierSIM_behav.wcfg -log simulate.log"
xsim csa_multiplierSIM_behav -key {Behavioral:sim_1:Functional:csa_multiplierSIM} -tclbatch csa_multiplierSIM.tcl -view /home/pmyers/Documents/F26files/3300/MultiplierCalculator/csa_multiplierSIM_behav.wcfg -log simulate.log

